// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1KXrW1x_j545h5d0yYIJDOBbeX-jDROw',
    appId: '1:1031262828366:web:3c81e6efc9e1b9d978501f',
    messagingSenderId: '1031262828366',
    projectId: 'blogapp-1cde0',
    authDomain: 'blogapp-1cde0.firebaseapp.com',
    storageBucket: 'blogapp-1cde0.appspot.com',
    measurementId: 'G-FV249NEM4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKJ4Bu4ABjPW1vhmVc2COejVr_DHLqRg',
    appId: '1:1031262828366:android:a19b61cd29e071d078501f',
    messagingSenderId: '1031262828366',
    projectId: 'blogapp-1cde0',
    storageBucket: 'blogapp-1cde0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnpoyimLUZwH3ta1B2VDFtcGOg9eFjBF0',
    appId: '1:1031262828366:ios:b13292e0f73beb3c78501f',
    messagingSenderId: '1031262828366',
    projectId: 'blogapp-1cde0',
    storageBucket: 'blogapp-1cde0.appspot.com',
    iosBundleId: 'com.example.dbProjBlogappui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnpoyimLUZwH3ta1B2VDFtcGOg9eFjBF0',
    appId: '1:1031262828366:ios:8498b6ce676dfccf78501f',
    messagingSenderId: '1031262828366',
    projectId: 'blogapp-1cde0',
    storageBucket: 'blogapp-1cde0.appspot.com',
    iosBundleId: 'com.example.dbProjBlogappui.RunnerTests',
  );
}
